### PR TITLE
Add option to seed the PRNG, use local PRNG instance instead of global

### PR DESCRIPTION
**Pull request by XANi**
Added option to specify seed, so the output can be made predictable.

Use local PRNG instance instead of global

### CODE REVIEW

**Comment by tomi77** [comment]
Please correct the **go19.go** file too

**Comment by tomi77** [comment]
> ./go19.go:56:6: (*LoremIpsum).shuffle redeclared in this block
> 	previous declaration at ./go19.go:34:6
> ./go19.go:56:6: method redeclared: LoremIpsum.shuffle
> 	method(*LoremIpsum) func(int, func(int, int))
> 	method(*LoremIpsum) func()
> ./go19.go:66:2: undefined: shuffle
> ./loremipsum.go:28:12: not enough arguments in call to li.shuffle
> 	have ()
> 	want (int, func(int, int))
> ./loremipsum.go:60:13: not enough arguments in call to li.shuffle
> 	have ()
> 	want (int, func(int, int))

Revert `func (li *LoremIpsum)shuffle(n int, swap func(i, j int))` to `func shuffle(n int, swap func(i, j int))` and probably all will be good.

**Comment by XANi** [comment]
That would go back to using global PRNG. Should be fixed now.

The Travis seems to be a bit broken for 1.10 tho:
```
PASS
coverage: 100.0% of statements
ok  	github.com/go-loremipsum/loremipsum	0.018s	coverage: 100.0% of statements
flag needs an argument: -repotoken
Usage: goveralls [options]
```

**Comment by tomi77** [comment]
It's problem with Coverals

**Pull request merged**
